import type {
    Candidate,
    ChartPoint,
    Interview,
    Job,
    PipelinePoint,
} from "../types";
import { C } from "./tokens";

export const JOBS: Job[] = [
  {
    id: 1,
    title: "Senior Product Designer",
    company: "Stripe",
    dept: "Product",
    type: "Full-time",
    level: "Senior",
    location: "San Francisco, CA",
    mode: "Hybrid",
    salary: "$130k–$170k",
    posted: "5 days ago",
    status: "Published",
    applicants: 28,
    views: 1240,
    match: 96,
    color: C.purple,
    tags: ["Figma", "Design Systems", "User Research"],
    shortlisted: 8,
  },
  {
    id: 2,
    title: "Frontend Engineer (React)",
    company: "Vercel",
    dept: "Engineering",
    type: "Full-time",
    level: "Mid-Senior",
    location: "Remote",
    mode: "Remote",
    salary: "$110k–$150k",
    posted: "8 days ago",
    status: "Published",
    applicants: 54,
    views: 2180,
    match: 91,
    color: C.info,
    tags: ["React", "TypeScript", "Next.js"],
    shortlisted: 14,
  },
  {
    id: 3,
    title: "Backend Engineer (Node.js)",
    company: "Linear",
    dept: "Engineering",
    type: "Full-time",
    level: "Mid-Senior",
    location: "New York, NY",
    mode: "Hybrid",
    salary: "$120k–$155k",
    posted: "12 days ago",
    status: "Published",
    applicants: 41,
    views: 1890,
    match: 88,
    color: C.success,
    tags: ["Node.js", "PostgreSQL", "AWS"],
    shortlisted: 11,
  },
  {
    id: 4,
    title: "Product Manager",
    company: "Notion",
    dept: "Product",
    type: "Full-time",
    level: "Senior",
    location: "San Francisco, CA",
    mode: "On-site",
    salary: "$140k–$180k",
    posted: "2 days ago",
    status: "Draft",
    applicants: 0,
    views: 0,
    match: 82,
    color: C.warning,
    tags: ["Strategy", "Roadmap", "Analytics"],
    shortlisted: 0,
  },
  {
    id: 5,
    title: "Data Scientist",
    company: "Anthropic",
    dept: "Data",
    type: "Full-time",
    level: "Mid",
    location: "Remote",
    mode: "Remote",
    salary: "$115k–$145k",
    posted: "18 days ago",
    status: "Published",
    applicants: 67,
    views: 2750,
    match: 79,
    color: C.textSec,
    tags: ["Python", "ML", "Statistics"],
    shortlisted: 19,
  },
];

export const CANDIDATES: Candidate[] = [
  {
    id: 1,
    name: "Marcus Chen",
    title: "Product Designer",
    univ: "Stanford University",
    location: "San Francisco, CA",
    match: 96,
    status: "Interview",
    job: "Senior Product Designer",
    avatar:
      "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=80&h=80&fit=crop&auto=format",
    skills: ["Figma", "Design Systems", "UX Research"],
    exp: "3 yrs",
    email: "marcus@stanford.edu",
  },
  {
    id: 2,
    name: "Sarah Johnson",
    title: "Frontend Engineer",
    univ: "MIT",
    location: "Boston, MA",
    match: 91,
    status: "Shortlisted",
    job: "Frontend Engineer (React)",
    avatar:
      "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=80&h=80&fit=crop&auto=format",
    skills: ["React", "TypeScript", "Next.js"],
    exp: "4 yrs",
    email: "s.johnson@mit.edu",
  },
  {
    id: 3,
    name: "James Kim",
    title: "Backend Engineer",
    univ: "UC Berkeley",
    location: "Oakland, CA",
    match: 88,
    status: "Applied",
    job: "Backend Engineer",
    avatar:
      "https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=80&h=80&fit=crop&auto=format",
    skills: ["Node.js", "PostgreSQL", "Redis"],
    exp: "3 yrs",
    email: "james@berkeley.edu",
  },
  {
    id: 4,
    name: "Aisha Patel",
    title: "Product Designer",
    univ: "CMU",
    location: "Pittsburgh, PA",
    match: 84,
    status: "Applied",
    job: "Senior Product Designer",
    avatar:
      "https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?w=80&h=80&fit=crop&auto=format",
    skills: ["Figma", "Motion Design", "UX Research"],
    exp: "2 yrs",
    email: "a.patel@cmu.edu",
  },
];

export const INTERVIEWS: Interview[] = [
  {
    id: 1,
    name: "Marcus Chen",
    role: "Senior Product Designer",
    type: "Technical Round",
    date: "Mar 28",
    time: "2:00 PM",
    duration: "60 min",
    status: "Confirmed",
    avatar:
      "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=40&h=40&fit=crop&auto=format",
  },
  {
    id: 2,
    name: "Sarah Johnson",
    role: "Frontend Engineer",
    type: "HR Screening",
    date: "Mar 29",
    time: "11:00 AM",
    duration: "30 min",
    status: "Pending",
    avatar:
      "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=40&h=40&fit=crop&auto=format",
  },
  {
    id: 3,
    name: "James Kim",
    role: "Backend Engineer",
    type: "System Design",
    date: "Apr 1",
    time: "3:00 PM",
    duration: "90 min",
    status: "Confirmed",
    avatar:
      "https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=40&h=40&fit=crop&auto=format",
  },
];

export const trendData: ChartPoint[] = [
  { month: "Oct", v: 32, h: 2 },
  { month: "Nov", v: 48, h: 3 },
  { month: "Dec", v: 29, h: 1 },
  { month: "Jan", v: 67, h: 4 },
  { month: "Feb", v: 85, h: 5 },
  { month: "Mar", v: 104, h: 6 },
];

export const pipelineData: PipelinePoint[] = [
  { name: "Applied", value: 284, color: C.info },
  { name: "Screened", value: 96, color: C.accent },
  { name: "Interview", value: 32, color: C.purple },
  { name: "Offer", value: 12, color: C.success },
  { name: "Hired", value: 6, color: "#2A6B54" },
];

export const weeklyData = [
  { day: "Mon", apps: 18 },
  { day: "Tue", apps: 34 },
  { day: "Wed", apps: 27 },
  { day: "Thu", apps: 42 },
  { day: "Fri", apps: 29 },
];

export const STUDENT = {
  name: "Marcus Chen",
  title: "Product Designer & CS Graduate",
  univ: "Stanford University",
  major: "Computer Science & HCI",
  gpa: "3.8",
  graduation: "May 2025",
  location: "San Francisco, CA",
  email: "marcus.chen@stanford.edu",
  phone: "+1 (415) 555-0192",
  portfolio: "marcuschen.design",
  github: "github.com/marcuschen",
  linkedin: "linkedin.com/in/marcuschen",
  avatar:
    "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&h=200&fit=crop&auto=format",
  completion: 85,
};

export const COMPANY = {
  name: "Nexus Technologies",
  industry: "Enterprise SaaS",
  size: "250–500 employees",
  location: "San Francisco, CA",
  founded: "2018",
  website: "nexustech.io",
  stage: "Series B · $45M raised",
  email: "careers@nexustech.io",
  phone: "+1 (415) 900-2400",
  about:
    "Nexus Technologies builds modern enterprise infrastructure that helps companies scale their operations intelligently. Backed by Sequoia Capital and Andreessen Horowitz, serving 600+ enterprise clients across 40 countries.",
  cover:
    "https://images.unsplash.com/photo-1715593949273-09009558300a?w=1200&h=280&fit=crop&auto=format",
  values: [
    "Move with urgency",
    "Build for humans",
    "Own the outcome",
    "Default to transparency",
  ],
  benefits: [
    "Competitive equity package",
    "Remote-friendly culture",
    "$6k annual learning budget",
    "Comprehensive health & dental",
    "Unlimited PTO",
    "Top-tier equipment",
  ],
};
