import { Ionicons } from "@expo/vector-icons";
import { router } from "expo-router";
import { useEffect, useMemo, useState } from "react";
import { ActivityIndicator, Alert, Pressable, RefreshControl, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import { C, F } from "../../constants/tokens";
import { deleteJob, getCompanyJobs } from "../../imports/api";
import { useSyncRefresh } from "../../context/SyncContext";

type Filter = "All" | "Published" | "Draft" | "Closed";
const unwrapJobs = (value: any): any[] => { const result = value?.data?.data ?? value?.data ?? value?.jobs ?? value ?? []; return Array.isArray(result) ? result : []; };
const jobStatus = (job: any) => { const value = String(job.status ?? (job.is_published ? "Published" : "Draft")); return value.toLowerCase() === "open" ? "Published" : value; };
const applicantCount = (job: any) => Number(job.applicants_count ?? job.applications_count ?? job.stats?.applicants ?? job.applicants?.length ?? 0);
function postedLabel(value?: string) { if (!value) return "Recently posted"; const date = new Date(value); if (Number.isNaN(date.getTime())) return "Recently posted"; const days = Math.max(0, Math.floor((Date.now() - date.getTime()) / 86400000)); if (days === 0) return "Posted today"; if (days === 1) return "Posted yesterday"; if (days < 7) return `Posted ${days} days ago`; const weeks = Math.floor(days / 7); return `Posted ${weeks} ${weeks === 1 ? "week" : "weeks"} ago`; }

export default function ManageJobs() {
  const [jobs, setJobs] = useState<any[]>([]); const [loading, setLoading] = useState(true); const [refreshing, setRefreshing] = useState(false); const [search, setSearch] = useState(""); const [filter, setFilter] = useState<Filter>("All");
  const load = async (refresh = false) => { if (refresh) setRefreshing(true); else setLoading(true); try { setJobs(unwrapJobs(await getCompanyJobs())); } catch { Alert.alert("Unable to load jobs", "Please try again."); } finally { setLoading(false); setRefreshing(false); } };
  useSyncRefresh(["jobs", "applications"], () => load(true));
  useEffect(() => { void load(); }, []);
  const visibleJobs = useMemo(() => { const query = search.trim().toLowerCase(); return jobs.filter((job) => { const matchesFilter = filter === "All" || jobStatus(job).toLowerCase() === filter.toLowerCase(); const matchesSearch = !query || [job.title, job.location, job.department].some((value) => String(value ?? "").toLowerCase().includes(query)); return matchesFilter && matchesSearch; }); }, [filter, jobs, search]);
  const published = jobs.filter((job) => jobStatus(job).toLowerCase() === "published").length; const applicants = jobs.reduce((sum, job) => sum + applicantCount(job), 0);
  const remove = (job: any) => Alert.alert("Delete job", `Delete ${job.title || "this job"}?`, [{ text: "Cancel", style: "cancel" }, { text: "Delete", style: "destructive", onPress: async () => { try { await deleteJob(job.id); await load(); } catch { Alert.alert("Could not delete job", "Please try again."); } } }]);
  if (loading) return <View style={styles.center}><ActivityIndicator size="large" color={C.accent} /><Text style={styles.loadingText}>Loading jobs...</Text></View>;
  return (
    <ScrollView style={styles.container} contentContainerStyle={styles.content} refreshControl={<RefreshControl refreshing={refreshing} onRefresh={() => void load(true)} tintColor={C.accent} />}>
      <View style={styles.header}><View style={styles.headerCopy}><Text style={styles.heading}>Manage Jobs</Text><Text style={styles.subtitle}>View and manage your job listings</Text></View><Pressable style={styles.create} onPress={() => router.push("/company/CreateJob")}><Ionicons name="add" size={18} color="#FFFFFF" /><Text style={styles.createText}>Post New Job</Text></Pressable></View>
      <View style={styles.statsRow}><Stat value={jobs.length} label="Total" /><Stat value={published} label="Published" /><Stat value={applicants} label="Applicants" /></View>
      <View style={styles.searchBox}><Ionicons name="search-outline" size={19} color={C.textMuted} /><TextInput value={search} onChangeText={setSearch} placeholder="Search jobs..." placeholderTextColor={C.textMuted} style={styles.searchInput} />{!!search && <Pressable onPress={() => setSearch("")}><Ionicons name="close-circle" size={19} color={C.textMuted} /></Pressable>}</View>
      <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.filters}>{(["All", "Published", "Draft", "Closed"] as Filter[]).map((item) => <Pressable key={item} onPress={() => setFilter(item)} style={[styles.filter, filter === item && styles.filterActive]}><Text style={[styles.filterText, filter === item && styles.filterTextActive]}>{item}</Text></Pressable>)}</ScrollView>
      {visibleJobs.length === 0 ? <View style={styles.empty}><Ionicons name="briefcase-outline" size={38} color={C.textMuted} /><Text style={styles.emptyTitle}>No jobs found</Text><Text style={styles.subtitle}>Try another search or create a new job.</Text></View> : visibleJobs.map((job) => (
        <View style={styles.card} key={job.id}>
          <View style={styles.cardTop}><View style={styles.jobIcon}><Text style={styles.jobIconText}>{String(job.title ?? "J").charAt(0).toUpperCase()}</Text></View><View style={styles.jobCopy}><Text style={styles.title} numberOfLines={2}>{job.title || "Untitled job"}</Text><Text style={styles.meta} numberOfLines={1}>{[job.department, job.employment_type ?? job.job_type].filter(Boolean).join(" · ") || job.location || "Job listing"}</Text></View><View style={styles.statusBadge}><Text style={styles.statusText}>{jobStatus(job)}</Text></View></View>
          <View style={styles.detailsRow}><Text style={styles.detailText}>{applicantCount(job)} applicants</Text><Text style={styles.detailText}>{Number(job.views ?? job.views_count ?? 0)} views</Text><Text style={styles.detailText}>{postedLabel(job.created_at ?? job.published_at)}</Text></View>
          <View style={styles.actions}><Pressable style={styles.viewButton} onPress={() => router.push({ pathname: "/company/JobDetails", params: { id: String(job.id) } })}><Text style={styles.viewText}>View</Text></Pressable><Pressable style={styles.outlineButton} onPress={() => router.push({ pathname: "/company/EditJob", params: { id: String(job.id) } })}><Ionicons name="create-outline" size={16} color={C.text} /><Text style={styles.outlineText}>Edit</Text></Pressable><Pressable style={styles.deleteButton} onPress={() => remove(job)}><Ionicons name="trash-outline" size={16} color={C.error} /><Text style={styles.deleteText}>Delete</Text></Pressable></View>
        </View>
      ))}
    </ScrollView>
  );
}
function Stat({ value, label }: { value: number; label: string }) { return <View style={styles.statCard}><Text style={styles.statValue}>{value}</Text><Text style={styles.statLabel}>{label}</Text></View>; }
const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: C.bg }, content: { padding: 18, paddingBottom: 40 }, center: { flex: 1, backgroundColor: C.bg, alignItems: "center", justifyContent: "center", gap: 10 }, loadingText: { color: C.textSec, fontFamily: F }, header: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: 12, marginBottom: 20 }, headerCopy: { flex: 1 }, heading: { fontSize: 25, fontWeight: "900", color: C.text, fontFamily: F }, subtitle: { color: C.textSec, fontSize: 12, marginTop: 4, fontFamily: F }, create: { flexDirection: "row", alignItems: "center", gap: 4, backgroundColor: C.accent, paddingHorizontal: 12, minHeight: 42, borderRadius: 11 }, createText: { color: "#FFFFFF", fontSize: 12, fontWeight: "800", fontFamily: F }, statsRow: { flexDirection: "row", gap: 9, marginBottom: 16 }, statCard: { flex: 1, minHeight: 72, flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 7, backgroundColor: C.surface, borderWidth: 1, borderColor: C.border, borderRadius: 14 }, statValue: { color: C.text, fontSize: 21, fontWeight: "900", fontFamily: F }, statLabel: { color: C.textSec, fontSize: 11, fontFamily: F }, searchBox: { height: 47, flexDirection: "row", alignItems: "center", gap: 8, backgroundColor: C.surface, borderWidth: 1, borderColor: C.border, borderRadius: 12, paddingHorizontal: 13 }, searchInput: { flex: 1, color: C.text, fontSize: 13, fontFamily: F }, filters: { gap: 8, paddingVertical: 12 }, filter: { minHeight: 39, justifyContent: "center", paddingHorizontal: 17, borderRadius: 11, backgroundColor: C.surface, borderWidth: 1, borderColor: C.border }, filterActive: { backgroundColor: C.accentLight, borderColor: C.accent }, filterText: { color: C.textSec, fontSize: 12, fontWeight: "700", fontFamily: F }, filterTextActive: { color: C.accentHover },
  card: { backgroundColor: C.surface, borderWidth: 1, borderColor: C.border, borderRadius: 17, padding: 15, marginBottom: 12 }, cardTop: { flexDirection: "row", alignItems: "flex-start", gap: 11 }, jobIcon: { width: 45, height: 45, borderRadius: 12, backgroundColor: C.accentLight, alignItems: "center", justifyContent: "center" }, jobIconText: { color: C.accentHover, fontSize: 18, fontWeight: "900", fontFamily: F }, jobCopy: { flex: 1 }, title: { color: C.text, fontSize: 15, fontWeight: "800", fontFamily: F }, meta: { color: C.textSec, fontSize: 11, marginTop: 4, fontFamily: F }, statusBadge: { backgroundColor: C.successBg, paddingHorizontal: 9, paddingVertical: 5, borderRadius: 8 }, statusText: { color: C.success, fontSize: 10, fontWeight: "800", fontFamily: F }, detailsRow: { flexDirection: "row", flexWrap: "wrap", gap: 14, marginTop: 14 }, detailText: { color: C.textSec, fontSize: 11, fontFamily: F }, actions: { flexDirection: "row", alignItems: "center", gap: 8, marginTop: 15 }, viewButton: { minHeight: 39, justifyContent: "center", paddingHorizontal: 16, borderRadius: 10, backgroundColor: C.accent }, viewText: { color: "#FFFFFF", fontSize: 12, fontWeight: "800", fontFamily: F }, outlineButton: { minHeight: 39, flexDirection: "row", alignItems: "center", gap: 5, paddingHorizontal: 13, borderRadius: 10, borderWidth: 1, borderColor: C.border }, outlineText: { color: C.text, fontSize: 12, fontWeight: "700", fontFamily: F }, deleteButton: { minHeight: 39, flexDirection: "row", alignItems: "center", gap: 5, paddingHorizontal: 8 }, deleteText: { color: C.error, fontSize: 12, fontWeight: "700", fontFamily: F }, empty: { alignItems: "center", backgroundColor: C.surface, borderWidth: 1, borderColor: C.border, borderRadius: 17, padding: 30, marginTop: 4 }, emptyTitle: { color: C.text, fontSize: 16, fontWeight: "800", marginTop: 10, fontFamily: F },
});
