import { useEffect, useState } from "react";
import { C, F } from "../../constants/tokens";
import { StatCard } from "../../components/ui";
import { CheckCircle, Clock, FileText, TrendingUp } from "lucide-react";
import { getAdminApplications } from "../../imports/api";
import { useSyncResourceVersion } from "../../sync/useSyncResourceVersion";

type Application = { id: number; status?: string; created_at?: string; student?: { name?: string }; student_name?: string; job?: { title?: string; company?: { company_name?: string } }; job_title?: string; company_name?: string };
const colors: Record<string, [string, string]> = { Interview: [C.purpleBg, C.purple], Shortlisted: [C.accentLight, C.accent], Applied: [C.infoBg, C.info], Hired: [C.successBg, C.success] };

export default function AdminApplications() {
  const applicationsSyncVersion = useSyncResourceVersion("applications");
  const [items, setItems] = useState<Application[]>([]); const [summary, setSummary] = useState<Record<string, number>>({}); const [loading, setLoading] = useState(true);
  useEffect(() => { getAdminApplications().then((response) => { const data = response?.data ?? response ?? {}; setItems(Array.isArray(data) ? data : data.applications ?? data.items ?? []); setSummary(data.statistics ?? data.summary ?? {}); }).catch((error) => console.error("Failed to load applications:", error)).finally(() => setLoading(false)); }, [applicationsSyncVersion]);
  const total = summary.total ?? summary.total_applications ?? items.length;
  return <div style={{ fontFamily: F, color: C.text }}><div style={{ marginBottom: 28 }}><h1 style={{ fontSize: 24, fontWeight: 700, margin: 0 }}>Applications</h1><p style={{ color: C.textSec, fontSize: 14, marginTop: 6 }}>Platform-wide application activity</p></div><div style={{ display: "grid", gridTemplateColumns: "repeat(4, 1fr)", gap: 16, marginBottom: 28 }}><StatCard label="Total Applications" value={loading ? "..." : String(total)} icon={FileText} color={C.info} /><StatCard label="This Month" value={loading ? "..." : String(summary.this_month ?? summary.monthly ?? 0)} icon={TrendingUp} color={C.accent} /><StatCard label="Successful Hires" value={loading ? "..." : String(summary.hired ?? summary.successful_hires ?? 0)} icon={CheckCircle} color={C.success} /><StatCard label="Pending Review" value={loading ? "..." : String(summary.pending ?? 0)} icon={Clock} color={C.warning} /></div><div style={{ background: C.surface, borderRadius: 20, border: `1px solid ${C.border}`, overflow: "hidden" }}><div style={{ padding: "16px 20px", borderBottom: `1px solid ${C.divider}` }}><h2 style={{ fontSize: 15, fontWeight: 700, margin: 0 }}>Recent Applications</h2></div><div style={{ display: "grid", gridTemplateColumns: "1.5fr 2fr 1.5fr 120px 110px", gap: 16, padding: "12px 20px", background: C.bg, borderBottom: `1px solid ${C.border}` }}>{["Candidate", "Job", "Company", "Status", "Date"].map((h) => <span key={h} style={{ fontSize: 11, fontWeight: 700, color: C.textMuted }}>{h.toUpperCase()}</span>)}</div>{loading ? <p style={{ padding: 28, textAlign: "center", color: C.textSec }}>Loading applications...</p> : items.length === 0 ? <p style={{ padding: 28, textAlign: "center", color: C.textSec }}>No applications found.</p> : items.map((item, i) => { const status = item.status ?? "Pending"; const [bg, color] = colors[status] ?? [C.warningBg, C.warning]; return <div key={item.id} style={{ display: "grid", gridTemplateColumns: "1.5fr 2fr 1.5fr 120px 110px", gap: 16, padding: "14px 20px", borderBottom: i < items.length - 1 ? `1px solid ${C.divider}` : "none", alignItems: "center" }}><span style={{ fontSize: 13, fontWeight: 600 }}>{item.student?.name ?? item.student_name ?? "—"}</span><span style={{ fontSize: 13, color: C.textSec }}>{item.job?.title ?? item.job_title ?? "—"}</span><span style={{ fontSize: 13, color: C.textSec }}>{item.job?.company?.company_name ?? item.company_name ?? "—"}</span><span style={{ padding: "4px 10px", borderRadius: 99, fontSize: 11, fontWeight: 600, background: bg, color, width: "fit-content" }}>{status}</span><span style={{ fontSize: 12, color: C.textMuted }}>{item.created_at ? new Date(item.created_at).toLocaleDateString() : "—"}</span></div>; })}</div></div>;
}
